#!/bin/sh
# /etc/init.d/S99aesdsocket

case "$1" in
    start)
        start-stop-daemon --start --exec /usr/bin/aesdsocket -b
        ;;
    stop)
        start-stop-daemon --stop --exec /usr/bin/aesdsocket
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0
